### ISSUE TITLE
V3.0 doesnt run 

### ISSUE THREAD

**Issue by Prady04** [BennyThadikaran/stock-pattern#35]
https://github.com/BennyThadikaran/stock-pattern/assets/71193926/c8fe4c25-944e-4597-b6d0-dbd778eadb4d

video attached.  it seems to be stuck on the main menu, any entry on the second prompt will result in crash

**Comment by BennyThadikaran** [comment]
You're running it via Visual Studio? Can you give it a try in Powershell directly. Just want to check if its specific to Visual Studio or Windows platform?

**Comment by BennyThadikaran** [comment]
I think i have dealt with this issue before on another program. It had something to do with the way threads are executed in Windows.

I will need to look it up. But it can be fixed

**Comment by BennyThadikaran** [comment]
Here is the explanation of the issue. https://stackoverflow.com/a/57811249 

I had this fixed in the previous version but i forgot why the `_name__ == '__main__' ` was there in the first place and removed it.
I will add it back along with a comment for future reference. I will give it a run in windows and post the update. Thanks for reporting the issue.

**Comment by BennyThadikaran** [comment]
Tested on Windows and confirmed fixed.

**Comment by Prady04** [comment]
It's the same behaviour in powershell as well.

regards,
Pradeep

**Comment by Prady04** [comment]
I added a main block around the process call and it worked fine.
as you suspected, I think it is related to lack of fork in windows,

**Comment by Prady04** [comment]
thanks a lot. it works fine now
